import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {TEST_KINDS,testKindConfig} from '../assets/tests/test-kind.js';
import {orderedListeningChoices} from '../assets/exam/listening/listening-view.js';
import {LISTENING_AUDIO_UNIT_KEY} from '../assets/exam/listening/audio-session.js';
import {buildPracticeQuestions} from '../assets/exam/practice-data.js';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
assert.deepEqual(TEST_KINDS.listening.parts.map(x=>x.part_no),[1,2,3,4]);
assert.deepEqual(TEST_KINDS.reading.parts.map(x=>x.part_no),[5,6,7]);
assert.deepEqual(TEST_KINDS.full.parts.map(x=>x.part_no),[1,2,3,4,5,6,7]);
assert.equal(testKindConfig('listening').parts[1].shuffle_choices,false);
assert.equal(testKindConfig('listening').parts[2].shuffle_choices,true);
assert.equal(LISTENING_AUDIO_UNIT_KEY,'listening:main');

const q={id:'q1',shuffle_choices:true,choices:['A','B','C','D'].map(key=>({key}))};
const a=orderedListeningChoices(q,'attempt-1');
const b=orderedListeningChoices(q,'attempt-1');
assert.deepEqual(a,b,'choice shuffle must be deterministic per attempt');
assert.deepEqual(a.map(x=>x.displayKey),['A','B','C','D'],'display labels must stay A-D after shuffle');
assert.deepEqual([...a.map(x=>x.originalKey)].sort(),['A','B','C','D'],'grading keys must be preserved');
const practiceQuestion=buildPracticeQuestions({parts:[{part_no:3,shuffle_choices:true}],questions:[{id:'p3q',part_no:3,source_number:32,source_order:1,choices:[{key:'A'},{key:'B'},{key:'C'},{key:'D'}]}],stimulus_groups:[]},[])[0];
assert.equal(practiceQuestion.shuffle_choices,true,'staff practice must use the same choice-shuffle setting as students');

const baseMigration=fs.readFileSync(path.join(root,'supabase/migrations/v1.18_listening_full_test.sql'),'utf8');
const singleMigration=fs.readFileSync(path.join(root,'supabase/migrations/v1.18b_single_listening_audio.sql'),'utf8');
for(const needle of ['test_kind','shuffle_choices','get_attempt_mode_v118','get_attempt_result'])assert.ok(baseMigration.includes(needle),`base migration missing ${needle}`);
for(const needle of ['listening_audio_storage_path','staff_set_listening_audio_v118b','get_listening_audio_v118b',"'listening:main'",'staff_clone_test_v118b','listening_audio_ready'])assert.ok(singleMigration.includes(needle),`single-audio migration missing ${needle}`);
const settings=fs.readFileSync(path.join(root,'assets/tests/listening-audio-settings.js'),'utf8');
assert.ok(settings.includes('Tải audio')&&settings.includes('staff_set_listening_audio_v118b'),'teacher must have a master-audio upload UI');
const authoring=fs.readFileSync(path.join(root,'assets/tests/authoring.js'),'utf8');
assert.ok(authoring.includes('partNo===2?["A","B","C"]'),'Part 2 must author exactly 3 choices');
const exam=fs.readFileSync(path.join(root,'assets/app-exam.js'),'utf8');
assert.ok(exam.includes('options.parts'),'Reading app must support Full Test Part 5-7 filtering');
const listeningExam=fs.readFileSync(path.join(root,'assets/exam/listening/listening-exam.js'),'utf8');
assert.ok(listeningExam.includes('get_listening_audio_v118b'),'student Listening must resolve one master audio file');
assert.ok(!listeningExam.includes('sameActiveUnit'),'question navigation must remain free while the master audio is playing');
const practice=fs.readFileSync(path.join(root,'assets/exam/listening/listening-practice.js'),'utf8');
assert.ok(practice.includes('staff_complete_practice_listening_v118'),'staff Full Test must persist Listening completion');
const view=fs.readFileSync(path.join(root,'assets/exam/listening/listening-view.js'),'utf8');
assert.ok(view.includes('Bấm một lần để nghe liên tục'),'Listening UI must explain one continuous audio playback');
assert.ok(view.includes('Number(q.part)>2&&q.content'),'Part 1-2 question transcript/text must stay hidden during Listening');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert.ok(index.includes('styles/listening.css'),'Listening stylesheet must be loaded');
console.log('V1.18 single-audio smoke OK: kinds, deterministic choices, upload UI, migration and integration contracts present.');
